### ISSUE TITLE
fails to build with containers-0.8: Ambiguous occurrence ‘edges’

### ISSUE THREAD

**Issue by juhp** [snowleopard/alga#323]
While trying to build HLS 2.12:

```
Building library for algebraic-graphs-0.7...
[ 1 of 29] Compiling Algebra.Graph.AdjacencyMap ( src/Algebra/Graph/AdjacencyMap.hs, dist/build/Algebra/Graph/AdjacencyMap.o, dist/build/Algebra/Graph/AdjacencyMap.dyn_o )
src/Algebra/Graph/AdjacencyMap.hs:531:32: error: [GHC-87543]
    Ambiguous occurrence ‘edges’.
    It could refer to
       either ‘Data.Tree.edges’,
              imported from ‘Data.Tree’ at src/Algebra/Graph/AdjacencyMap.hs:58:1-16,
           or ‘Algebra.Graph.AdjacencyMap.edges’,
              defined at src/Algebra/Graph/AdjacencyMap.hs:323:1.
    |
531 |                      (_:ys) -> edges (zip xs ys)
    |                                ^^^^^

[ 4 of 29] Compiling Algebra.Graph.Internal ( src/Algebra/Graph/Internal.hs, dist/build/Algebra/Graph/Internal.o, dist/build/Algebra/Graph/Internal.dyn_o )
[ 9 of 29] Compiling Algebra.Graph.Label ( src/Algebra/Graph/Label.hs, dist/build/Algebra/Graph/Label.o, dist/build/Algebra/Graph/Label.dyn_o )
src/Algebra/Graph/Label.hs:121:10: warning: [GHC-30606] [-Wredundant-constraints]
    • Redundant constraint: Num a
    • In the instance declaration for ‘Show (NonNegative a)’
    |
121 | instance (Num a, Show a) => Show (NonNegative a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Algebra/Graph/Label.hs:329:10: warning: [GHC-30606] [-Wredundant-constraints]
    • Redundant constraint: Monoid a
    • In the instance declaration for ‘Monoid (Minimum a)’
    |
329 | instance (Monoid a, Ord a) => Monoid (Minimum a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

https://download.copr.fedorainfracloud.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/09963223-haskell-language-server-ghc9.14/builder-live.log.gz

**Comment by jwaldmann** [comment]
well the reason is not the version of ghc, but of containers (0.8), see their CHANGELOG and https://github.com/haskell/containers/pull/1109

**Comment by snowleopard** [comment]
Thanks! Could someone propose a patch?

**Comment by tonyday567** [comment]
https://hackage-content.haskell.org/package/containers-0.8/docs/Data-Tree.html#v:edges

containers added edges in 0.8, so just need to hide Data.Tree.edges at the site.

**Comment by jwaldmann** [comment]
"just need to hide" - sure, but someone has to do the work.

On closer inspection, @PiDelport  already did: alga main (this repo) contains 86534a23a31c223845ad4ee1d627c2ad38c52e93 so the current version (0.8) just needs a hackage release?

again, "just needs" ...

**Comment by tonyday567** [comment]
@jwaldmann I do my bit. alga is on my long list of allow-newer and I was checking in on status. Not my bug - I was just checking in noting status. Read the thread, downloaded alga, built it, it's fine, built it in my context, fine. It's a transitive concern I could care less about, but I read the thread. You, with your fancy name and school-maam attitude, had withheld the reason, that edges had been introduced as a name, and I love, love alga with all my heart, so yes I write a casual note in case it helped. And now you want to school a stranger on what it means to do work. To disparage my use of just for a cheap bit? Consider me schooled.

**Comment by juhp** [comment]
Okay, funnily enough this was already fixed in #317.

This issue makes it hard to build HLS for ghc9.14.

So we just need a new release on Hackage, please

*Okay I only repeated what jwaldmann said*

**Comment by snowleopard** [comment]
Hi all, my apologies for the delay. Hobby projects tend to lose the fight for time to my family these days 👨‍👧‍👦 

I've built, tested, packaged and uploaded the latest version to Hackage: https://hackage.haskell.org/package/algebraic-graphs-0.8.

Thanks all for the pings!

**Comment by juhp** [comment]
Thank you very much @snowleopard - we understand and appreciate your effort!
