### ISSUE TITLE
Tests failed to build with QuickCheck 2.14.2

### ISSUE THREAD

**Issue by felixonmars** [snowleopard/alga#265]
```
[ 1 of 22] Compiling Algebra.Graph.Test.Arbitrary ( test/Algebra/Graph/Test/Arbitrary.hs, dist/build/test-alga/test-alga-tmp/Algebra/Graph/Test/Arbitrary.dyn_o )

test/Algebra/Graph/Test/Arbitrary.hs:220:10: error:
    Duplicate instance declarations:
      instance Arbitrary a => Arbitrary (Tree a)
        -- Defined at test/Algebra/Graph/Test/Arbitrary.hs:220:10
      instance Arbitrary a => Arbitrary (Tree a)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
    |
220 | instance Arbitrary a => Arbitrary (Tree a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
